### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  id: TextureResolution
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.TextureResolution.High
  - ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Low
  - ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Mid
  - ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Ultra
  langs:
  - csharp
  - vb
  name: TextureResolution
  nameWithType: TextureResolution
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  type: Enum
  source:
    id: TextureResolution
    path: ''
    startLine: 7256
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  syntax:
    content: public enum TextureResolution
    content.vb: Public Enum TextureResolution
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Low
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Low
  id: Low
  parent: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  langs:
  - csharp
  - vb
  name: Low
  nameWithType: TextureResolution.Low
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Low
  type: Field
  source:
    id: Low
    path: ''
    startLine: 7258
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  syntax:
    content: Low = 512
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Mid
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Mid
  id: Mid
  parent: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  langs:
  - csharp
  - vb
  name: Mid
  nameWithType: TextureResolution.Mid
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Mid
  type: Field
  source:
    id: Mid
    path: ''
    startLine: 7260
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  syntax:
    content: Mid = 1024
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.High
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.TextureResolution.High
  id: High
  parent: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  langs:
  - csharp
  - vb
  name: High
  nameWithType: TextureResolution.High
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.High
  type: Field
  source:
    id: High
    path: ''
    startLine: 7262
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  syntax:
    content: High = 2048
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Ultra
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Ultra
  id: Ultra
  parent: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  langs:
  - csharp
  - vb
  name: Ultra
  nameWithType: TextureResolution.Ultra
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution.Ultra
  type: Field
  source:
    id: Ultra
    path: ''
    startLine: 7264
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  syntax:
    content: Ultra = 4096
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: TextureResolution
  nameWithType: TextureResolution
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
