### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  id: PrecomputedBakeCameraSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  langs:
  - csharp
  - vb
  name: PrecomputedBakeCameraSettings
  nameWithType: PrecomputedBakeCameraSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  type: Class
  source:
    id: PrecomputedBakeCameraSettings
    path: ''
    startLine: 7171
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nBase bake settings for use in camera based generation\n"
  example: []
  syntax:
    content: 'public abstract class PrecomputedBakeCameraSettings : PrecomputedBaseBakeSettings'
    content.vb: Public MustInherit Class PrecomputedBakeCameraSettings Inherits PrecomputedBaseBakeSettings
  inheritance:
  - System.Object
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  derivedClasses:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  id: CellDepthTestDensity
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  langs:
  - csharp
  - vb
  name: CellDepthTestDensity
  nameWithType: PrecomputedBakeCameraSettings.CellDepthTestDensity
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  type: Field
  source:
    id: CellDepthTestDensity
    path: ''
    startLine: 7176
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nHow samples should be distributed along the cell box\n"
  example: []
  syntax:
    content: public Vector3Int CellDepthTestDensity
    return:
      type: Global.Vector3Int
    content.vb: Public CellDepthTestDensity As Vector3Int
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  id: CellDepthTestDensityOffset
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  langs:
  - csharp
  - vb
  name: CellDepthTestDensityOffset
  nameWithType: PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  type: Field
  source:
    id: CellDepthTestDensityOffset
    path: ''
    startLine: 7184
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nHow samples should be offseted along the cell box\n"
  example: []
  syntax:
    content: public Vector3 CellDepthTestDensityOffset
    return:
      type: Global.Vector3
    content.vb: Public CellDepthTestDensityOffset As Vector3
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  id: VisibleTransparent
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  langs:
  - csharp
  - vb
  name: VisibleTransparent
  nameWithType: PrecomputedBakeCameraSettings.VisibleTransparent
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  type: Field
  source:
    id: VisibleTransparent
    path: ''
    startLine: 7190
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nTransparent materials are visible and use them in bake\n"
  example: []
  syntax:
    content: public bool VisibleTransparent
    return:
      type: System.Boolean
    content.vb: Public VisibleTransparent As Boolean
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: PrecomputedBaseBakeSettings
  nameWithType: PrecomputedBaseBakeSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Global.Vector3Int
  isExternal: true
  name: Vector3Int
  nameWithType: Vector3Int
  fullName: Vector3Int
- uid: Global.Vector3
  isExternal: true
  name: Vector3
  nameWithType: Vector3
  fullName: Vector3
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
