### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings
  id: PrecomputedBakeIdCubemapSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorFormat
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorToFloatDivisor
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.TextureResolution
  langs:
  - csharp
  - vb
  name: PrecomputedBakeIdCubemapSettings
  nameWithType: PrecomputedBakeIdCubemapSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings
  type: Class
  source:
    id: PrecomputedBakeIdCubemapSettings
    path: ''
    startLine: 7230
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nBake camera settings used to precompute Occlusion Data\n"
  example: []
  syntax:
    content: 'public class PrecomputedBakeIdCubemapSettings : PrecomputedBakeCameraSettings'
    content.vb: Public Class PrecomputedBakeIdCubemapSettings Inherits PrecomputedBakeCameraSettings
  inheritance:
  - System.Object
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  inheritedMembers:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.TextureResolution
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.TextureResolution
  id: TextureResolution
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings
  langs:
  - csharp
  - vb
  name: TextureResolution
  nameWithType: PrecomputedBakeIdCubemapSettings.TextureResolution
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.TextureResolution
  type: Field
  source:
    id: TextureResolution
    path: ''
    startLine: 7237
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nTexture Resolution to generate cube map and equirect\n"
  example: []
  syntax:
    content: public TextureResolution TextureResolution
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
    content.vb: Public TextureResolution As TextureResolution
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorFormat
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorFormat
  id: ColorFormat
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings
  langs:
  - csharp
  - vb
  name: ColorFormat
  nameWithType: PrecomputedBakeIdCubemapSettings.ColorFormat
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorFormat
  type: Field
  source:
    id: ColorFormat
    path: ''
    startLine: 7244
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\n Color format used to generate cube map and equirect texture.\n<p>Reduce only if encountering artifacts or your GPU do not support default R16G16B16A16_UNorm</p>\n"
  example: []
  syntax:
    content: public GraphicsFormat ColorFormat
    return:
      type: Global.GraphicsFormat
    content.vb: Public ColorFormat As GraphicsFormat
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorToFloatDivisor
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorToFloatDivisor
  id: ColorToFloatDivisor
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings
  langs:
  - csharp
  - vb
  name: ColorToFloatDivisor
  nameWithType: PrecomputedBakeIdCubemapSettings.ColorToFloatDivisor
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeIdCubemapSettings.ColorToFloatDivisor
  type: Field
  source:
    id: ColorToFloatDivisor
    path: ''
    startLine: 7253
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nBecause all shaders are using float but colors in band of 0-255 int we need to divide index of the object\nto be a float 0-1. Keep default 32 unless your total amount of objects is above 262144 renderers or lower\nthe value for less complex scenes if you know you will have less renderers to decrease possibility of\nfloat rounding error.\n"
  example: []
  syntax:
    content: public int ColorToFloatDivisor
    return:
      type: System.Int32
    content.vb: Public ColorToFloatDivisor As Integer
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: PrecomputedBaseBakeSettings
  nameWithType: PrecomputedBaseBakeSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: PrecomputedBakeCameraSettings
  nameWithType: PrecomputedBakeCameraSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  name: CellDepthTestDensity
  nameWithType: PrecomputedBakeCameraSettings.CellDepthTestDensity
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  name: CellDepthTestDensityOffset
  nameWithType: PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  name: VisibleTransparent
  nameWithType: PrecomputedBakeCameraSettings.VisibleTransparent
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: TextureResolution
  nameWithType: TextureResolution
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
- uid: Global.GraphicsFormat
  commentId: '!:Global.GraphicsFormat'
  isExternal: true
  name: GraphicsFormat
  nameWithType: GraphicsFormat
  fullName: GraphicsFormat
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
