### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  id: BakeAlgorithm
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  - ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  langs:
  - csharp
  - vb
  name: BakeAlgorithm
  nameWithType: BakeAlgorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  type: Enum
  source:
    id: BakeAlgorithm
    path: D:\Repo_D\Prographers\perfect-culling\OcclusionCulling\Assets\ProgLibrary\PrecomputedCulling\Scripts\PrecomputedCulling\Settings\PrecomputedSettingsArea.cs
    startLine: 13
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: Types of algorithms
  example: []
  syntax:
    content: public enum BakeAlgorithm
    content.vb: Public Enum BakeAlgorithm
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  id: FrustumDepthTest
  parent: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  langs:
  - csharp
  - vb
  name: FrustumDepthTest
  nameWithType: BakeAlgorithm.FrustumDepthTest
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  type: Field
  source:
    id: FrustumDepthTest
    path: D:\Repo_D\Prographers\perfect-culling\OcclusionCulling\Assets\ProgLibrary\PrecomputedCulling\Scripts\PrecomputedCulling\Settings\PrecomputedSettingsArea.cs
    startLine: 15
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  syntax:
    content: FrustumDepthTest = 0
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  id: ColorIdCubeMap
  parent: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  langs:
  - csharp
  - vb
  name: ColorIdCubeMap
  nameWithType: BakeAlgorithm.ColorIdCubeMap
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  type: Field
  source:
    id: ColorIdCubeMap
    path: D:\Repo_D\Prographers\perfect-culling\OcclusionCulling\Assets\ProgLibrary\PrecomputedCulling\Scripts\PrecomputedCulling\Settings\PrecomputedSettingsArea.cs
    startLine: 19
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: Map texture colors based algorithm
  example: []
  syntax:
    content: ColorIdCubeMap = 1
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  href: ProgLibrary.html
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
    href: ProgLibrary.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
    href: ProgLibrary.PrecomputedCulling.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
    href: ProgLibrary.PrecomputedCulling.Settings.html
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
    href: ProgLibrary.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
    href: ProgLibrary.PrecomputedCulling.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
    href: ProgLibrary.PrecomputedCulling.Settings.html
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  parent: ProgLibrary.PrecomputedCulling.Settings
  href: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.html
  name: BakeAlgorithm
  nameWithType: BakeAlgorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
