### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  id: PrecomputedSettingsArea
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  langs:
  - csharp
  - vb
  name: PrecomputedSettingsArea
  nameWithType: PrecomputedSettingsArea
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  type: Class
  source:
    id: PrecomputedSettingsArea
    path: ''
    startLine: 7644
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nGlobal occlusion settings to be displayed in the editor\n"
  example: []
  syntax:
    content: public class PrecomputedSettingsArea
    content.vb: Public Class PrecomputedSettingsArea
  inheritance:
  - System.Object
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  id: Algorithm
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  langs:
  - csharp
  - vb
  name: Algorithm
  nameWithType: PrecomputedSettingsArea.Algorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  type: Field
  source:
    id: Algorithm
    path: ''
    startLine: 7655
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nCurrent selected precomputed algorithm\n"
  example: []
  syntax:
    content: public BakeAlgorithm Algorithm
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
    content.vb: Public Algorithm As BakeAlgorithm
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  id: PrecomputedBakeCameraSettings
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  langs:
  - csharp
  - vb
  name: PrecomputedBakeCameraSettings
  nameWithType: PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  type: Field
  source:
    id: PrecomputedBakeCameraSettings
    path: ''
    startLine: 7668
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nBake settings used to compute Occlusion Data with Frustum camera\n"
  example: []
  syntax:
    content: public PrecomputedBakeCameraSettings PrecomputedBakeCameraSettings
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
    content.vb: Public PrecomputedBakeCameraSettings As PrecomputedBakeCameraSettings
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: BakeAlgorithm
  nameWithType: BakeAlgorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: PrecomputedBakeCameraSettings
  nameWithType: PrecomputedBakeCameraSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
