### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  id: PrecomputedDataSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeSprites
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTerrain
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTransparent
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensity
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensityOffset
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellsDivisions
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.IsGlobalQuality
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.Priority
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.TextureResolution
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.VariantsSettings
  langs:
  - csharp
  - vb
  name: PrecomputedDataSettings
  nameWithType: PrecomputedDataSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  type: Class
  source:
    id: PrecomputedDataSettings
    path: ''
    startLine: 7292
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nMain precomputed settings\n"
  example: []
  syntax:
    content: 'public class PrecomputedDataSettings : ScriptableObject'
    content.vb: Public Class PrecomputedDataSettings Inherits ScriptableObject
  inheritance:
  - System.Object
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.VariantsSettings
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.VariantsSettings
  id: VariantsSettings
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: VariantsSettings
  nameWithType: PrecomputedDataSettings.VariantsSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.VariantsSettings
  type: Field
  source:
    id: VariantsSettings
    path: ''
    startLine: 7299
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nVariants configurations\n"
  example: []
  syntax:
    content: public List<PrecomputedSceneVariantData> VariantsSettings
    return:
      type: Global.List{PrecomputedSceneVariantData}
    content.vb: Public VariantsSettings As List(Of PrecomputedSceneVariantData)
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider
  commentId: P:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider
  id: DataProvider
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: DataProvider
  nameWithType: PrecomputedDataSettings.DataProvider
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider
  type: Property
  source:
    id: DataProvider
    path: ''
    startLine: 7309
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\n<xref href=\"ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings._dataProvider\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: public IPrecomputedDataProvider DataProvider { get; set; }
    parameters: []
    return:
      type: Global.IPrecomputedDataProvider
    content.vb: Public Property DataProvider As IPrecomputedDataProvider
  overload: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider*
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellsDivisions
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellsDivisions
  id: CellsDivisions
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: CellsDivisions
  nameWithType: PrecomputedDataSettings.CellsDivisions
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellsDivisions
  type: Field
  source:
    id: CellsDivisions
    path: ''
    startLine: 7318
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nAmount of cells in this volume in 3d dimension\n"
  example: []
  syntax:
    content: public Vector3Int CellsDivisions
    return:
      type: Global.Vector3Int
    content.vb: Public CellsDivisions As Vector3Int
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensity
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensity
  id: CellDepthTestDensity
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: CellDepthTestDensity
  nameWithType: PrecomputedDataSettings.CellDepthTestDensity
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensity
  type: Field
  source:
    id: CellDepthTestDensity
    path: ''
    startLine: 7323
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nBake spots\n"
  example: []
  syntax:
    content: public Vector3Int CellDepthTestDensity
    return:
      type: Global.Vector3Int
    content.vb: Public CellDepthTestDensity As Vector3Int
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensityOffset
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensityOffset
  id: CellDepthTestDensityOffset
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: CellDepthTestDensityOffset
  nameWithType: PrecomputedDataSettings.CellDepthTestDensityOffset
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.CellDepthTestDensityOffset
  type: Field
  source:
    id: CellDepthTestDensityOffset
    path: ''
    startLine: 7328
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nBake spots offset\n"
  example: []
  syntax:
    content: public Vector3 CellDepthTestDensityOffset
    return:
      type: Global.Vector3
    content.vb: Public CellDepthTestDensityOffset As Vector3
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.Priority
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.Priority
  id: Priority
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: PrecomputedDataSettings.Priority
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.Priority
  type: Field
  source:
    id: Priority
    path: ''
    startLine: 7333
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nPriority, which occlusion area is used when two are overlapping, higher priority will be used\n"
  example: []
  syntax:
    content: public int Priority
    return:
      type: System.Int32
    content.vb: Public Priority As Integer
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.TextureResolution
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.TextureResolution
  id: TextureResolution
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: TextureResolution
  nameWithType: PrecomputedDataSettings.TextureResolution
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.TextureResolution
  type: Field
  source:
    id: TextureResolution
    path: ''
    startLine: 7338
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nDefault quality texture during bake\n"
  example: []
  syntax:
    content: public TextureResolution TextureResolution
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
    content.vb: Public TextureResolution As TextureResolution
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.IsGlobalQuality
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.IsGlobalQuality
  id: IsGlobalQuality
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: IsGlobalQuality
  nameWithType: PrecomputedDataSettings.IsGlobalQuality
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.IsGlobalQuality
  type: Field
  source:
    id: IsGlobalQuality
    path: ''
    startLine: 7343
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nUse Default quality texture options as global\n"
  example: []
  syntax:
    content: public bool IsGlobalQuality
    return:
      type: System.Boolean
    content.vb: Public IsGlobalQuality As Boolean
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTransparent
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTransparent
  id: BakeTransparent
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: BakeTransparent
  nameWithType: PrecomputedDataSettings.BakeTransparent
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTransparent
  type: Field
  source:
    id: BakeTransparent
    path: ''
    startLine: 7348
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nTransparent objects should get occluded\n"
  example: []
  syntax:
    content: public bool BakeTransparent
    return:
      type: System.Boolean
    content.vb: Public BakeTransparent As Boolean
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeSprites
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeSprites
  id: BakeSprites
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: BakeSprites
  nameWithType: PrecomputedDataSettings.BakeSprites
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeSprites
  type: Field
  source:
    id: BakeSprites
    path: ''
    startLine: 7353
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nOcclusion Culling should see sprites\n"
  example: []
  syntax:
    content: public bool BakeSprites
    return:
      type: System.Boolean
    content.vb: Public BakeSprites As Boolean
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTerrain
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTerrain
  id: BakeTerrain
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings
  langs:
  - csharp
  - vb
  name: BakeTerrain
  nameWithType: PrecomputedDataSettings.BakeTerrain
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.BakeTerrain
  type: Field
  source:
    id: BakeTerrain
    path: ''
    startLine: 7358
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nOcclusion Culling should calculate terrain\n"
  example: []
  syntax:
    content: public bool BakeTerrain
    return:
      type: System.Boolean
    content.vb: Public BakeTerrain As Boolean
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Global.List{PrecomputedSceneVariantData}
  commentId: '!:Global.List{PrecomputedSceneVariantData}'
  definition: Global.List`1
  name: List<PrecomputedSceneVariantData>
  nameWithType: List<PrecomputedSceneVariantData>
  fullName: List<PrecomputedSceneVariantData>
  nameWithType.vb: List(Of PrecomputedSceneVariantData)
  fullName.vb: List(Of PrecomputedSceneVariantData)
  name.vb: List(Of PrecomputedSceneVariantData)
  spec.csharp:
  - uid: Global.List`1
    name: List
    isExternal: true
  - name: <
  - uid: Global.PrecomputedSceneVariantData
    name: PrecomputedSceneVariantData
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Global.PrecomputedSceneVariantData
    name: PrecomputedSceneVariantData
    isExternal: true
  - name: )
- uid: Global.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: List<>
  nameWithType.vb: List(Of )
  fullName.vb: List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: Global.List`1
    name: List
    isExternal: true
  - name: <
  - name: ''
  - name: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: ''
  - name: )
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings._dataProvider
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings._dataProvider
  isExternal: true
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider*
  commentId: Overload:ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider
  name: DataProvider
  nameWithType: PrecomputedDataSettings.DataProvider
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedDataSettings.DataProvider
- uid: Global.IPrecomputedDataProvider
  isExternal: true
  name: IPrecomputedDataProvider
  nameWithType: IPrecomputedDataProvider
  fullName: IPrecomputedDataProvider
- uid: Global.Vector3Int
  isExternal: true
  name: Vector3Int
  nameWithType: Vector3Int
  fullName: Vector3Int
- uid: Global.Vector3
  isExternal: true
  name: Vector3
  nameWithType: Vector3
  fullName: Vector3
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.TextureResolution
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: TextureResolution
  nameWithType: TextureResolution
  fullName: ProgLibrary.PrecomputedCulling.Settings.TextureResolution
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
