### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings
  id: PrecomputedBakeTargetedFrustumSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.DepthMapResolution
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.FrustumCalculationsNumber
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.TargetItemTooCloseTreshold
  langs:
  - csharp
  - vb
  name: PrecomputedBakeTargetedFrustumSettings
  nameWithType: PrecomputedBakeTargetedFrustumSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings
  type: Class
  source:
    id: PrecomputedBakeTargetedFrustumSettings
    path: D:\Repo_D\Prographers\perfect-culling\OcclusionCulling\Assets\ProgLibrary\PrecomputedCulling\Scripts\PrecomputedCulling\Settings\PrecomputedBakeTargetedFrustumSettings.cs
    startLine: 11
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: Bake settings used to compute Occlusion Data vis <see cref="!:TargetedFrustumCamera"></see>
  example: []
  syntax:
    content: >-
      [Serializable]

      public class PrecomputedBakeTargetedFrustumSettings : PrecomputedBakeCameraSettings
    content.vb: >-
      <Serializable>

      Public Class PrecomputedBakeTargetedFrustumSettings Inherits PrecomputedBakeCameraSettings
  inheritance:
  - System.Object
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  inheritedMembers:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.DepthMapResolution
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.DepthMapResolution
  id: DepthMapResolution
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings
  langs:
  - csharp
  - vb
  name: DepthMapResolution
  nameWithType: PrecomputedBakeTargetedFrustumSettings.DepthMapResolution
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.DepthMapResolution
  type: Field
  source:
    id: DepthMapResolution
    path: D:\Repo_D\Prographers\perfect-culling\OcclusionCulling\Assets\ProgLibrary\PrecomputedCulling\Scripts\PrecomputedCulling\Settings\PrecomputedBakeTargetedFrustumSettings.cs
    startLine: 17
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: Resolution of depth screenshot
  example: []
  syntax:
    content: public Vector2Int DepthMapResolution
    return:
      type: UnityEngine.Vector2Int
    content.vb: Public DepthMapResolution As Vector2Int
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.TargetItemTooCloseTreshold
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.TargetItemTooCloseTreshold
  id: TargetItemTooCloseTreshold
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings
  langs:
  - csharp
  - vb
  name: TargetItemTooCloseTreshold
  nameWithType: PrecomputedBakeTargetedFrustumSettings.TargetItemTooCloseTreshold
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.TargetItemTooCloseTreshold
  type: Field
  source:
    id: TargetItemTooCloseTreshold
    path: D:\Repo_D\Prographers\perfect-culling\OcclusionCulling\Assets\ProgLibrary\PrecomputedCulling\Scripts\PrecomputedCulling\Settings\PrecomputedBakeTargetedFrustumSettings.cs
    startLine: 24
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: >-
    Some objects that are close are not possible to cover in camera view frustum.

    Use this value to determine how close is too close
  example: []
  syntax:
    content: public float TargetItemTooCloseTreshold
    return:
      type: System.Single
      description: ''
    content.vb: Public TargetItemTooCloseTreshold As Single
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.FrustumCalculationsNumber
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.FrustumCalculationsNumber
  id: FrustumCalculationsNumber
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings
  langs:
  - csharp
  - vb
  name: FrustumCalculationsNumber
  nameWithType: PrecomputedBakeTargetedFrustumSettings.FrustumCalculationsNumber
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeTargetedFrustumSettings.FrustumCalculationsNumber
  type: Field
  source:
    id: FrustumCalculationsNumber
    path: D:\Repo_D\Prographers\perfect-culling\OcclusionCulling\Assets\ProgLibrary\PrecomputedCulling\Scripts\PrecomputedCulling\Settings\PrecomputedBakeTargetedFrustumSettings.cs
    startLine: 31
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: >-
    Number of frustum calculations to get proper frustum value over an object.

    Default 2 number should be more then enough and does not require change,

    unless you are experiencing critical errors with the bake generation.
  example: []
  syntax:
    content: public int FrustumCalculationsNumber
    return:
      type: System.Int32
    content.vb: Public FrustumCalculationsNumber As Integer
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  href: ProgLibrary.html
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
    href: ProgLibrary.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
    href: ProgLibrary.PrecomputedCulling.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
    href: ProgLibrary.PrecomputedCulling.Settings.html
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
    href: ProgLibrary.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
    href: ProgLibrary.PrecomputedCulling.html
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
    href: ProgLibrary.PrecomputedCulling.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  href: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings.html
  name: PrecomputedBaseBakeSettings
  nameWithType: PrecomputedBaseBakeSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBaseBakeSettings
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  href: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.html
  name: PrecomputedBakeCameraSettings
  nameWithType: PrecomputedBakeCameraSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  href: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.html#ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
  name: CellDepthTestDensity
  nameWithType: PrecomputedBakeCameraSettings.CellDepthTestDensity
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensity
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  href: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.html#ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  name: CellDepthTestDensityOffset
  nameWithType: PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.CellDepthTestDensityOffset
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  href: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.html#ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
  name: VisibleTransparent
  nameWithType: PrecomputedBakeCameraSettings.VisibleTransparent
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings.VisibleTransparent
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine.Vector2Int
  commentId: T:UnityEngine.Vector2Int
  parent: UnityEngine
  isExternal: true
  name: Vector2Int
  nameWithType: Vector2Int
  fullName: UnityEngine.Vector2Int
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
