### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  id: BakeAlgorithm
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  - ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  langs:
  - csharp
  - vb
  name: BakeAlgorithm
  nameWithType: BakeAlgorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  type: Enum
  source:
    id: BakeAlgorithm
    path: ''
    startLine: 7632
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nTypes of algorithms\n"
  example: []
  syntax:
    content: public enum BakeAlgorithm
    content.vb: Public Enum BakeAlgorithm
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  id: FrustumDepthTest
  parent: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  langs:
  - csharp
  - vb
  name: FrustumDepthTest
  nameWithType: BakeAlgorithm.FrustumDepthTest
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.FrustumDepthTest
  type: Field
  source:
    id: FrustumDepthTest
    path: ''
    startLine: 7634
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  syntax:
    content: FrustumDepthTest = 0
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  id: ColorIdCubeMap
  parent: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  langs:
  - csharp
  - vb
  name: ColorIdCubeMap
  nameWithType: BakeAlgorithm.ColorIdCubeMap
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm.ColorIdCubeMap
  type: Field
  source:
    id: ColorIdCubeMap
    path: ''
    startLine: 7638
  assemblies:
  - cs.temp.dll
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nMap texture colors based algorithm\n"
  example: []
  syntax:
    content: ColorIdCubeMap = 1
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
  spec.csharp:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
  spec.vb:
  - uid: ProgLibrary
    name: ProgLibrary
  - name: .
  - uid: ProgLibrary.PrecomputedCulling
    name: PrecomputedCulling
  - name: .
  - uid: ProgLibrary.PrecomputedCulling.Settings
    name: Settings
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: BakeAlgorithm
  nameWithType: BakeAlgorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
