### YamlMime:ManagedReference
items:
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  id: PrecomputedSettingsArea
  parent: ProgLibrary.PrecomputedCulling.Settings
  children:
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  - ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  langs:
  - csharp
  - vb
  name: PrecomputedSettingsArea
  nameWithType: PrecomputedSettingsArea
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  type: Class
  source:
    remote:
      path: OcclusionCulling/Assets/Scripts/ProgLibrary/PrecomputedCulling/PrecomputedCulling/Settings/PrecomputedSettingsArea.cs
      branch: develop
      repo: git@bitbucket.org:prographers/perfect-culling.git
    id: PrecomputedSettingsArea
    path: ../../../Unity/perfect-culling/OcclusionCulling/Assets/Scripts/ProgLibrary/PrecomputedCulling/PrecomputedCulling/Settings/PrecomputedSettingsArea.cs
    startLine: 25
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nGlobal occlusion settings to be displayed in the editor\n"
  example: []
  syntax:
    content: >-
      [Serializable]

      public class PrecomputedSettingsArea
    content.vb: >-
      <Serializable>

      Public Class PrecomputedSettingsArea
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  id: Algorithm
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  langs:
  - csharp
  - vb
  name: Algorithm
  nameWithType: PrecomputedSettingsArea.Algorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.Algorithm
  type: Field
  source:
    remote:
      path: OcclusionCulling/Assets/Scripts/ProgLibrary/PrecomputedCulling/PrecomputedCulling/Settings/PrecomputedSettingsArea.cs
      branch: develop
      repo: git@bitbucket.org:prographers/perfect-culling.git
    id: Algorithm
    path: ../../../Unity/perfect-culling/OcclusionCulling/Assets/Scripts/ProgLibrary/PrecomputedCulling/PrecomputedCulling/Settings/PrecomputedSettingsArea.cs
    startLine: 36
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nCurrent selected precomputed algorithm\n"
  example: []
  syntax:
    content: >-
      [HideInInspector]

      [BoxGroup]

      [OnValueChanged("OnAlgorithmChange", false)]

      public BakeAlgorithm Algorithm
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
    content.vb: >-
      <HideInInspector>

      <BoxGroup>

      <OnValueChanged("OnAlgorithmChange", False)>

      Public Algorithm As BakeAlgorithm
  attributes:
  - type: UnityEngine.HideInInspector
    ctor: UnityEngine.HideInInspector.#ctor
    arguments: []
  - type: Sirenix.OdinInspector.BoxGroupAttribute
    ctor: Sirenix.OdinInspector.BoxGroupAttribute.#ctor
    arguments: []
  - type: Sirenix.OdinInspector.OnValueChangedAttribute
    ctor: Sirenix.OdinInspector.OnValueChangedAttribute.#ctor(System.String,System.Boolean)
    arguments:
    - type: System.String
      value: OnAlgorithmChange
    - type: System.Boolean
      value: false
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  commentId: F:ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  id: PrecomputedBakeCameraSettings
  parent: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea
  langs:
  - csharp
  - vb
  name: PrecomputedBakeCameraSettings
  nameWithType: PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedSettingsArea.PrecomputedBakeCameraSettings
  type: Field
  source:
    remote:
      path: OcclusionCulling/Assets/Scripts/ProgLibrary/PrecomputedCulling/PrecomputedCulling/Settings/PrecomputedSettingsArea.cs
      branch: develop
      repo: git@bitbucket.org:prographers/perfect-culling.git
    id: PrecomputedBakeCameraSettings
    path: ../../../Unity/perfect-culling/OcclusionCulling/Assets/Scripts/ProgLibrary/PrecomputedCulling/PrecomputedCulling/Settings/PrecomputedSettingsArea.cs
    startLine: 49
  assemblies:
  - PrecomputedCulling
  namespace: ProgLibrary.PrecomputedCulling.Settings
  summary: "\nBake settings used to compute Occlusion Data with Frustum camera\n"
  example: []
  syntax:
    content: >-
      [BoxGroup]

      [HideLabel]

      [InlineProperty]

      [ShowInInspector]

      [HideReferenceObjectPicker]

      [SerializeReference]

      public PrecomputedBakeCameraSettings PrecomputedBakeCameraSettings
    return:
      type: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
    content.vb: >-
      <BoxGroup>

      <HideLabel>

      <InlineProperty>

      <ShowInInspector>

      <HideReferenceObjectPicker>

      <SerializeReference>

      Public PrecomputedBakeCameraSettings As PrecomputedBakeCameraSettings
  attributes:
  - type: Sirenix.OdinInspector.BoxGroupAttribute
    ctor: Sirenix.OdinInspector.BoxGroupAttribute.#ctor
    arguments: []
  - type: Sirenix.OdinInspector.HideLabelAttribute
    ctor: Sirenix.OdinInspector.HideLabelAttribute.#ctor
    arguments: []
  - type: Sirenix.OdinInspector.InlinePropertyAttribute
    ctor: Sirenix.OdinInspector.InlinePropertyAttribute.#ctor
    arguments: []
  - type: Sirenix.OdinInspector.ShowInInspectorAttribute
    ctor: Sirenix.OdinInspector.ShowInInspectorAttribute.#ctor
    arguments: []
  - type: Sirenix.OdinInspector.HideReferenceObjectPickerAttribute
    ctor: Sirenix.OdinInspector.HideReferenceObjectPickerAttribute.#ctor
    arguments: []
  - type: UnityEngine.SerializeReference
    ctor: UnityEngine.SerializeReference.#ctor
    arguments: []
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: ProgLibrary.PrecomputedCulling.Settings
  commentId: N:ProgLibrary.PrecomputedCulling.Settings
  name: ProgLibrary.PrecomputedCulling.Settings
  nameWithType: ProgLibrary.PrecomputedCulling.Settings
  fullName: ProgLibrary.PrecomputedCulling.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: BakeAlgorithm
  nameWithType: BakeAlgorithm
  fullName: ProgLibrary.PrecomputedCulling.Settings.BakeAlgorithm
- uid: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  commentId: T:ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
  parent: ProgLibrary.PrecomputedCulling.Settings
  name: PrecomputedBakeCameraSettings
  nameWithType: PrecomputedBakeCameraSettings
  fullName: ProgLibrary.PrecomputedCulling.Settings.PrecomputedBakeCameraSettings
